### ISSUE TITLE
IllegalStateException: Asynchronous getNearbyEntities 

### ISSUE THREAD

**Issue by EncryptSL** [MinecordNetwork/BeautyIndicator#1]
Server Version:  Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Nedokážu ti blíže specifikovat kde je v tvém pluginu problém ale věřím že ho najdeš. Když jsem se koukal do zdroje tak mi nepřišlo že by v něm bylo něco špatně ale zřejmě je a něco se mu nelíbí. 

`[22:34:46 WARN]: [BeautyIndicator] Plugin BeautyIndicator 1.7 generated an exception while executing task 323                      java.lang.IllegalStateException: Asynchronous getNearbyEntities!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-209]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.getNearbyEntities(CraftEntity.java:531) ~[patched_1.14.4.jar:git-Paper-209]
        at net.minecord.beautyindicator.controller.PlayerController.getEntityLookingAt(PlayerController.java:13) ~[?:?]         at net.minecord.beautyindicator.listener.CombatListener$1.run(CombatListener.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-209]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-209]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-209]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by delacry** [comment]
Thanks! Looks that newer server versions give you a warning when you try to get nearby entities in another thread, should be fixed.
